### ISSUE TITLE
Contrast course specific and program wide changes

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/teaching_responsibility#31]
> I think it would help to elaborate on the relationship between course specific changes and program wide changes. In the “Example lesson(s) of lots of practice” section (pp. 14-15), the authors outline how the principles of reproducibility have been fully integrated across courses in the Master of Data Science program, which strongly incentivizes students to practice what they’re taught over the duration of the program. Is it the case that these changes were adopted across the program simultaneously? Or were changes implemented in select courses initially and only more widely after some period of time? If it’s the latter, I would be very interested to know how students performed when the principles of reproducibility were not widely integrated throughout the curriculum. In other schools, it might be the case that there is limited appetite or support for a coordinated change across the curriculum. For readers in this situation, it would be beneficial to know more about the authors experiences implementing these changes only among select courses.

**Comment by ttimbers** [comment]
> Is it the case that these changes were adopted across the program simultaneously?

Yes, it is this. Since year 1 in the program, we chose to adopt version control as they way students hand in their homework for all courses. This was done to give students lots of practice. To make this feasible, postdoctoral teaching and learning fellows were hired (i.e., Mike and I) to help faculty implement this in their courses even if those faculty themselves were not familiar with version control (Mike and I were hired for other reasons too, but this was part of our job in the early days).

I think our teaching team model really helps us doing program-wide changes like this. This stems from our shared vision for the program (which was drafted collaboratively by the team), our once-per term academic retreats where we reflect on how things went, and our frequent communication and collaboration at our weekly academic meetings.
