### ISSUE TITLE
Elaborate on how Jenny Bryan's teaching method was adapted

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/teaching_responsibility#37]
> In the “Letting them fail (in a controlled manner)” section (p. 7), the authors note that they adapted Jenny Bryan’s teaching method to scale up the exercise. It would be helpful to elaborate on this point so that the reader understands exactly how the exercise was altered/adapted.

**Comment by ttimbers** [comment]
Jenny had the students pair up and trade projects - so run the other person's project and they tried to run theirs. Problems with this at large scale could be:
- some student pairs used the same dependencies and so there was no failure
- there was no immediate "success" example to contrast this with

The way we do it, we pick an obscure package, or packages (e.g., `cowsay`) that none of the students should have so that they will all have trouble running the project without reproducibility tools. Also, we then shortly after provide them with a project with reproducibility tools so that they can have success and contrast the two experiences.
